FROM golang:1.20-bullseye AS builder

ARG VERSION="devel"
WORKDIR /go/src/github.com/metriqorg/go
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
ENV GOFLAGS="-ldflags=-X=github.com/metriqorg/go/support/app.version=${VERSION}-(built-from-source)"
RUN go install github.com/metriqorg/go/services/orbitr

FROM ubuntu:22.04
ARG GRAVITY_VERSION 
ENV GRAVITY_VERSION=${GRAVITY_VERSION:-*}
ENV GRAVITY_BINARY_PATH /usr/bin/stellar-core

ENV DEBIAN_FRONTEND=noninteractive
# ca-certificates are required to make tls connections
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl wget gnupg apt-utils
RUN wget -qO - https://apt.stellar.org/SDF.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true apt-key add -
RUN echo "deb https://apt.stellar.org focal stable" >/etc/apt/sources.list.d/SDF.list
RUN echo "deb https://apt.stellar.org focal unstable" >/etc/apt/sources.list.d/SDF-unstable.list
RUN apt-get update && apt-get install -y stellar-core=${GRAVITY_VERSION}
RUN apt-get clean

COPY --from=builder /go/bin/orbitr ./

ENTRYPOINT ["./orbitr"]
    
